sudo: required
services: 
  - docker

before_install:
  - docker build -t xandyk/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true xandyk/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-1-904832385693"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
